global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["sports-field-booking-prometheus:9090"]

  - job_name: "SportsFieldBooking"
    scrape_interval: 2s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:8888"]
